### ISSUE TITLE
Debian and Ubuntu packages

### ISSUE THREAD

**Issue by blackandred** [nicolas-van/multirun#11]
Hi! Thanks for this great work! I hope it will be spreaded widely as a great, simple alternative to supervisord!

I wonder if there are plans for Debian and Ubuntu packages, so it could be easily installed on non-alpine images?

**Comment by nicolas-van** [comment]
Thanks for the support.

Unfortunately it would take *a lot* of work on my side to have it published in Debian's repository. It's also a very obscure process that makes it excessively hard for a non-Debian maintainer to start trying. For alpine I didn't even do it, another user named @TBK did all the job.

So, if a Debian maintainer wants to do the job I would be glad to review and merge whatever is needed to make it happen. In the mean time the binaries are still very easy to use on all architectures, even compiling is very easy due to the lack of any dependency.

**Comment by blackandred** [comment]
I understand. Thanks :slightly_smiling_face:
