### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by pyrsmk** [nicolas-van/multirun#15]
Does it handle zombie processes correctly like Tini (or any other init manager) ?

Some info on the subject for those who may be interested : https://github.com/krallin/tini/issues/8#issuecomment-146135930

edit: typo

**Comment by blackandred** [comment]
If multirun detects that at least one process died, then exits all other processes. But I don't know if a zombie process means that process has `exit > 0`. Maybe its worth to check it and implement if its missing.

**Comment by pyrsmk** [comment]
Does multirun detects **all** exited processes or only the ones it's handling (from the `multirun` command) ? Because those zombie processes will mostly come from child processes.

**Comment by nicolas-van** [comment]
multirun only detects the state of the processes it creates. So no, it will never attempt to reap child processes. It's true that it would be an interesting feature to add, I'll look at it.

**Comment by nicolas-van** [comment]
I made some tests by creating a C program that voluntarily creates zombie processes before dying. I wasn't able to simulate a case were the zombie processes persisted despite the fact their parent died. This is probably due to multirun's behavior which is to wait for all children (regardless if they were original children or adopted ones) and just plainly ignore the ones it didn't spawned.

So in fact yes, it kind of does handle the zombie processes problem. Although it is not voluntarily but by chance.

Due to the fact I have some doubts regarding the fact that this behavior may be random and/or platform dependent and/or Linux version dependent (the man pages are quite difficult to understand) and also the fact that I completely understand people's concerns about zombies (I would be very sad to learn that I'm the cause of a zombie epidemy) I added some more checks inspired by tiny's source code and some other generic zombie handlers I could find in man pages.

So now we should be safe about zombies.

Unfortunately, after my tests, I figured that the is actually a more concerning problem: alive children.

If an original child spawns some children and then dies, multirun's behavior is to make sure all original children are killed but it does not take care of their descendants. That's a huge concern, as alive children are way more dangerous than zombies. Zombies are not very hard to kill, just shoot them in the head and you're done. Alive children are way smarter. They can hide from you and steal your food.

I'll be sure to improve multirun in order to make sure that whenever it decides to kill one of its children it does the job correctly and take care of all their descendant. I promise you, **none of them will survive**.

**Comment by pyrsmk** [comment]
> I promise you, none of them will survive.

Yeah, kill them all! ☠️

**Comment by pyrsmk** [comment]
Anyway, thanks for your responsiveness. Multirun is the only way init system that is **really** simple to use and that can handle several processes. So, thanks for the time you pass on it!

**Comment by nicolas-van** [comment]
Ok, version 1.1.0 released which should take care of all the potential problems I've seen. See the release note here: https://github.com/nicolas-van/multirun/releases/tag/1.1.0

**Comment by pyrsmk** [comment]
Wow, that was fast !

**Comment by nicolas-van** [comment]
It's the week end 😛
